#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

USE_PROCD=1
START=99

APP=hucon_server

SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
PROG=/opt/hucon/start_server.sh

start_service() {
	if [ ! -z ${IPKG_INSTROOT+x} ];
		then echo "In build environment - doing nothing."; 
	else
		procd_open_instance 
		procd_set_param command "$PROG"
		procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
		procd_close_instance
	fi
}
 
reload_service()
{
	echo "Explicitly restarting service, are you sure you need this?"
	stop
	start
}