#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Onion Corporation
START=11

USE_PROCD=1

start_service() {
	if [ ! -z ${IPKG_INSTROOT+x} ];
		then echo "In build environment - doing nothing."; 
	else
		procd_open_instance 
		procd_set_param command "sh /opt/hucon/i2c_led.sh on"
		procd_close_instance
	fi
}
