#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Onion Corporation
START=11

USE_PROCD=1


start_service() {
        procd_open_instance
        procd_set_param command sh /root/hucon/i2c_led.sh on
#        procd_append_param command [COMMAND ARGUMENTS]     # optionally append command parameters
#        procd_set_param respawn  # respawn the service if it exits
#        procd_set_param stdout 1 # forward stdout of the command to logd
#        procd_set_param stderr 1 # same for stderr
        procd_close_instance
}
